# Generated by Django 3.0.2 on 2020-02-14 06:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'A user is already registered with this email address'}, max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Cours'), ('TD', 'Travail Dirigé'), ('TP', 'Travail Pratique'), ('P', 'Projet')], max_length=2)),
                ('vh', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnneeUniv',
            fields=[
                ('annee_univ', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('encours', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('grade', models.CharField(blank=True, choices=[('MAB', 'Maître Assistant B'), ('MAA', 'Maître Assistant A'), ('MCB', 'Maître de Conférences B'), ('MCA', 'Maître de Conférences A'), ('PR', 'Professeur')], max_length=4, null=True)),
                ('charge_statut', models.DecimalField(decimal_places=2, default=288, max_digits=5)),
                ('statut', models.CharField(blank=True, choices=[('A', 'En activité'), ('D', 'Mis en disponibilité'), ('T', 'Détachement'), ('M', 'Congé de Maladie'), ('B', 'Congé de Maternité')], default='A', max_length=1, null=True)),
                ('edt', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=30, null=True)),
                ('nom_a', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom_a', models.CharField(blank=True, max_length=50, null=True)),
                ('lieu_naissance_a', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CF', 'Contrôle Final'), ('CI', 'Contrôle Intérmédiaire'), ('INT', 'Interrogation'), ('TP', 'Travail Pratique'), ('PR', 'Projet'), ('CC', 'Contrôle Continu')], max_length=3)),
                ('ponderation', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.AnneeUniv')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, choices=[('G01', 'Groupe 01'), ('G02', 'Groupe 02'), ('G03', 'Groupe 03'), ('G04', 'Groupe 04'), ('G05', 'Groupe 05'), ('G06', 'Groupe 06'), ('G07', 'Groupe 07'), ('G08', 'Groupe 08'), ('G09', 'Groupe 09'), ('G10', 'Groupe 10'), ('G11', 'Groupe 11'), ('G12', 'Groupe 12')], max_length=3, null=True)),
                ('edt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('C', 'En cours'), ('F', 'Abandon'), ('T', 'Terminé'), ('M', 'Maladie')], max_length=1)),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rang', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decision_jury', models.CharField(blank=True, choices=[('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('R', 'Redouble'), ('F', 'Abandon')], max_length=2, null=True)),
                ('obs_jury', models.CharField(blank=True, max_length=50, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Etudiant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Formation')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscrits', to='scolar.Groupe')),
                ('tuteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('titre', models.CharField(max_length=80)),
                ('titre_a', models.CharField(blank=True, max_length=80, null=True)),
                ('titre_en', models.CharField(blank=True, max_length=80, null=True)),
                ('coef', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('edition', models.CharField(blank=True, default='2012', max_length=5, null=True)),
                ('vh_cours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vh_td', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pre_requis', models.TextField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('travail_perso', models.TextField(blank=True, null=True)),
                ('bibliographie', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_eliminatoire', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('coordinateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Enseignant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Formation')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=2, null=True)),
                ('ordre', models.IntegerField()),
                ('nb_semaines', models.IntegerField(blank=True, default=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Periode')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('type', models.CharField(choices=[('F', 'Fondamentale'), ('M', 'Méthodologique'), ('T', 'Transversale'), ('D', 'Découverte')], max_length=1)),
                ('nature', models.CharField(choices=[('OBL', 'Obligatoire'), ('OPT', 'Optionnelle')], max_length=3, null=True)),
                ('coef', models.IntegerField(null=True)),
                ('matieres', models.ManyToManyField(blank=True, to='scolar.Matiere')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='scolar.PeriodeProgramme')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D'), ('E', 'Section E')], max_length=1, null=True)),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Formation')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('absences_enseignants', models.ManyToManyField(blank=True, to='scolar.Enseignant')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Activite')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moy', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('moy_post_delib', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='scolar.Inscription')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('titre', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Specialite')),
            ],
        ),
        migrations.AddField(
            model_name='periodeprogramme',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='scolar.Programme'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_post_delib', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Evaluation')),
                ('resultat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scolar.Resultat')),
            ],
        ),
        migrations.CreateModel(
            name='ModulesSuivis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saisie_notes', models.CharField(choices=[('N', 'Pas encore'), ('C', 'En cours'), ('T', 'Terminé')], default='N', max_length=1)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_suivis', to='scolar.Groupe')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_suivis', to='scolar.Module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Periode'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='option',
            field=models.ManyToManyField(blank=True, to='scolar.UE'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Section'),
        ),
        migrations.AddField(
            model_name='formation',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Programme'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='scolar.Module'),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Enseignement'), ('C', 'Encadrement'), ('S', 'Surveillance'), ('A', 'Responsabilite Administrative'), ('M', 'Mission'), ('R', 'Réunion')], max_length=1)),
                ('obs', models.CharField(blank=True, max_length=50, null=True)),
                ('vh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vh_eq_td', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repeter_chaque_semaine', models.BooleanField(blank=True, default=False, null=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Activite')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Enseignant')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Periode')),
                ('realisee_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='scolar.Enseignant')),
            ],
        ),
        migrations.AddField(
            model_name='activite',
            name='assuree_par',
            field=models.ManyToManyField(related_name='enseignants', to='scolar.Enseignant'),
        ),
        migrations.AddField(
            model_name='activite',
            name='cible',
            field=models.ManyToManyField(blank=True, related_name='groupes', to='scolar.Groupe'),
        ),
        migrations.AddField(
            model_name='activite',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Module'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justif', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True, max_length=50, null=True)),
                ('date_justif', models.DateField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Etudiant')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Seance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='resultat',
            constraint=models.UniqueConstraint(fields=('inscription', 'module'), name='inscription-module'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('evaluation', 'resultat'), name='evaluation-resultat'),
        ),
        migrations.AddConstraint(
            model_name='modulessuivis',
            constraint=models.UniqueConstraint(fields=('module', 'groupe'), name='module-groupe'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('etudiant', 'formation'), name='etudiant-formation'),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.UniqueConstraint(fields=('code', 'section'), name='groupe-section'),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('programme', 'annee_univ'), name='programme-annee_univ'),
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.UniqueConstraint(fields=('etudiant', 'seance'), name='etudiant-seance'),
        ),
    ]
