# Generated by Django 3.0.2 on 2020-02-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0002_auto_20200215_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.PeriodeProgramme'),
        ),
        migrations.AlterField(
            model_name='modulessuivis',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.PeriodeProgramme'),
        ),
    ]
