# Generated by Django 3.0.2 on 2020-02-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0003_auto_20200215_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeAnnee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_univ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.AnneeUniv')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Periode')),
            ],
        ),
        migrations.AlterField(
            model_name='charge',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.PeriodeAnnee'),
        ),
    ]
