# Generated by Django 3.0.2 on 2020-02-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0005_resultat_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
