# Generated by Django 3.0.2 on 2020-02-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0006_auto_20200216_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='scolar.Module')),
                ('resultat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Resultat')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='periodeannee',
            name='preface_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(choices=[('++', "Tout à fait d'accord"), ('+', "D'accord"), ('-', "Pas d'accord"), ('--', 'En total désaccord')], max_length=2)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Feedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Question')),
            ],
        ),
    ]
