# Generated by Django 3.0.2 on 2020-02-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0007_auto_20200217_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineConnaissance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='ddc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.DomaineConnaissance'),
        ),
    ]
