# Generated by Django 3.0.2 on 2020-02-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0011_auto_20200228_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='decision_jury',
            field=models.CharField(blank=True, choices=[('C', 'En cours'), ('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('R', 'Redouble'), ('F', 'Abandon'), ('M', 'Maladie'), ('N', 'Non Admis')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='note_eliminatoire',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=4, null=True),
        ),
    ]
