# Generated by Django 3.0.2 on 2020-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0015_etudiant_public_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='type',
            field=models.CharField(choices=[('C', 'Cours'), ('TD', 'Travail Dirigé'), ('TP', 'Travail Pratique'), ('P', 'Projet'), ('E_CI', 'CI'), ('E_CF', 'CF'), ('E_CR', 'CR'), ('E_In', 'Interrogation'), ('E_TP', 'Test TP')], max_length=5),
        ),
    ]
