# Generated by Django 3.0.2 on 2020-03-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0016_auto_20200316_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='linkdin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
