# Generated by Django 3.0.2 on 2020-03-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0018_auto_20200317_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('intitule', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('intitule', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('MOD', 'Modélisation'), ('MET', 'Méthodologie'), ('TEC', 'Technique'), ('OPE', 'Opérationnel')], max_length=5)),
                ('competence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Competence')),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceFamily',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='MatiereCompetenceElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('B', 'Base'), ('I', 'Intermédiaire'), ('A', 'Avancé')], max_length=1)),
                ('objectif', models.TextField(blank=True, null=True)),
                ('competence_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.CompetenceElement')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Matiere')),
            ],
        ),
        migrations.AddField(
            model_name='competence',
            name='competence_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.CompetenceFamily'),
        ),
        migrations.AddConstraint(
            model_name='matierecompetenceelement',
            constraint=models.UniqueConstraint(fields=('matiere', 'competence_element'), name='matiere-competence-element'),
        ),
        migrations.AddConstraint(
            model_name='competenceelement',
            constraint=models.UniqueConstraint(fields=('code', 'competence'), name='competence-element-competence'),
        ),
        migrations.AddConstraint(
            model_name='competence',
            constraint=models.UniqueConstraint(fields=('code', 'competence_family'), name='competence-competence-family'),
        ),
    ]
