# Generated by Django 3.0.2 on 2020-03-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0019_auto_20200318_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matierecompetenceelement',
            name='objectif',
        ),
        migrations.AddField(
            model_name='competenceelement',
            name='objectif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competence',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='competence',
            name='intitule',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='competenceelement',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='competenceelement',
            name='intitule',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='competencefamily',
            name='intitule',
            field=models.CharField(max_length=120),
        ),
    ]
