# Generated by Django 3.0.2 on 2020-03-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0020_auto_20200318_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='competence_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competences', to='scolar.CompetenceFamily'),
        ),
    ]
