# Generated by Django 3.0.2 on 2020-03-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0021_auto_20200319_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenceelement',
            name='competence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competence_elements', to='scolar.Competence'),
        ),
    ]
