# Generated by Django 3.0.2 on 2020-03-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0023_auto_20200322_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
