# Generated by Django 3.0.2 on 2020-03-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0024_auto_20200322_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='bureau',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
