# Generated by Django 3.0.2 on 2020-03-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0025_auto_20200322_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='statut',
            field=models.CharField(blank=True, choices=[('P', 'Permanent'), ('V', 'Vacataire'), ('R', 'Retraité'), ('A', 'Associé')], default='P', max_length=1, null=True),
        ),
    ]
