# Generated by Django 3.0.2 on 2020-03-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0026_enseignant_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='absences_enseignants',
        ),
        migrations.CreateModel(
            name='AbsenceEnseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justif', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True, max_length=50, null=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Enseignant')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Seance')),
                ('seance_remplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remplacement', to='scolar.Seance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='absenceenseignant',
            constraint=models.UniqueConstraint(fields=('enseignant', 'seance'), name='enseignant-seance'),
        ),
    ]
