# Generated by Django 3.0.2 on 2020-03-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0027_auto_20200327_0701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absence',
            new_name='AbsenceEtudiant',
        ),
    ]
