# Generated by Django 3.0.2 on 2020-03-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0028_auto_20200327_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenceenseignant',
            name='date_justif',
            field=models.DateField(blank=True, null=True),
        ),
    ]
