# Generated by Django 3.0.2 on 2020-03-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0030_auto_20200327_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semainier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.PositiveSmallIntegerField(choices=[(1, 'Semaine 1'), (2, 'Semaine 2'), (3, 'Semaine 3'), (4, 'Semaine 4'), (5, 'Semaine 5'), (6, 'Semaine 6'), (7, 'Semaine 7'), (8, 'Semaine 8'), (9, 'Semaine 9'), (10, 'Semaine 10'), (11, 'Semaine 11'), (12, 'Semaine 12'), (13, 'Semaine 13'), (14, 'Semaine 14'), (15, 'Semaine 15')])),
                ('activite_cours', models.CharField(blank=True, max_length=255, null=True)),
                ('activite_dirigee', models.TextField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('objectifs', models.CharField(blank=True, max_length=255, null=True)),
                ('matiere_competence_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.MatiereCompetenceElement')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Module')),
            ],
        ),
        migrations.AddConstraint(
            model_name='semainier',
            constraint=models.UniqueConstraint(fields=('module', 'semaine'), name='module-semaine'),
        ),
    ]
