# Generated by Django 3.0.2 on 2020-03-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0031_auto_20200328_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Inscription'),
        ),
        migrations.AddField(
            model_name='module',
            name='mode_projet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='projet_na',
            field=models.BooleanField(default=False),
        ),
    ]
