# Generated by Django 3.0.2 on 2020-03-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0032_auto_20200329_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='mode_projet',
        ),
        migrations.AddField(
            model_name='matiere',
            name='mode_projet',
            field=models.BooleanField(default=False),
        ),
    ]
