# Generated by Django 3.0.2 on 2020-03-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0033_auto_20200329_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='resultat',
        ),
    ]
