# Generated by Django 3.0.2 on 2020-03-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0034_remove_feedback_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='activite_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
