# Generated by Django 3.0.2 on 2020-03-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0035_inscription_activite_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='pfe',
            field=models.BooleanField(default=False),
        ),
    ]
