# Generated by Django 3.0.2 on 2020-03-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0036_matiere_pfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='type',
            field=models.CharField(choices=[('CF', 'Contrôle Final'), ('CI', 'Contrôle Intérmédiaire'), ('INT', 'Interrogation'), ('TP', 'Travail Pratique'), ('PR', 'Projet'), ('CC', 'Contrôle Continu'), ('Rapporteur', 'PFE: Evaluation du rapport'), ('Jury', 'PFE: Evaluation du jury'), ('Encadreur', "PFE: Evaluation de l'encadreur")], max_length=15),
        ),
        migrations.CreateModel(
            name='EvaluationCompetenceElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_au_groupe', models.BooleanField(default=False)),
                ('ponderation', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('competence_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.CompetenceElement')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_elements', to='scolar.Evaluation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='evaluationcompetenceelement',
            constraint=models.UniqueConstraint(fields=('evaluation', 'competence_element'), name='evaluation_competence_element'),
        ),
    ]
