# Generated by Django 3.0.2 on 2020-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0037_auto_20200331_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='code',
            field=models.CharField(blank=True, choices=[('G01', 'Groupe 01'), ('G02', 'Groupe 02'), ('G03', 'Groupe 03'), ('G04', 'Groupe 04'), ('G05', 'Groupe 05'), ('G06', 'Groupe 06'), ('G07', 'Groupe 07'), ('G08', 'Groupe 08'), ('G09', 'Groupe 09'), ('G10', 'Groupe 10'), ('G11', 'Groupe 11'), ('G12', 'Groupe 12')], max_length=10, null=True),
        ),
    ]
