# Generated by Django 3.0.2 on 2020-03-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0038_auto_20200331_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='type',
            field=models.CharField(choices=[('C', 'Cours'), ('TD', 'Travail Dirigé'), ('TP', 'Travail Pratique'), ('P', 'Projet'), ('E_CI', 'CI'), ('E_CF', 'CF'), ('E_CR', 'CR'), ('E_In', 'Interrogation'), ('E_TP', 'Test TP'), ('PFE_Enc', 'Encadrement PFE'), ('PFE_Sout', 'Soutenance PFE')], max_length=10),
        ),
    ]
