# Generated by Django 3.0.2 on 2020-04-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0039_auto_20200331_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='mention',
            field=models.CharField(blank=True, choices=[('T', 'Très Bien'), ('B', 'Bien'), ('A', 'Assez Bien'), ('P', 'Passable'), ('N', 'Non Admis')], max_length=1, null=True),
        ),
    ]
