# Generated by Django 3.0.2 on 2020-04-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0040_inscription_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='mention',
            field=models.CharField(blank=True, choices=[('T', 'Très Bien'), ('B', 'Bien'), ('A', 'Assez Bien'), ('P', 'Passable'), ('N', 'Non Admis')], default='N', max_length=1, null=True),
        ),
    ]
