# Generated by Django 3.0.2 on 2020-04-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0041_auto_20200402_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='matiere_ues', to='scolar.Matiere'),
        ),
    ]
