# Generated by Django 3.0.2 on 2020-04-03 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0042_auto_20200402_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionPeriode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moy', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rang', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Groupe')),
            ],
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='moyenne',
        ),
        migrations.CreateModel(
            name='ResultatUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moy', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('inscription_periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_ues', to='scolar.InscriptionPeriode')),
                ('ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.UE')),
            ],
        ),
        migrations.AddField(
            model_name='inscriptionperiode',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_periodes', to='scolar.Inscription'),
        ),
        migrations.AddField(
            model_name='inscriptionperiode',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Periode'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='resultat_ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultat_matieres', to='scolar.ResultatUE'),
        ),
        migrations.AddConstraint(
            model_name='resultatue',
            constraint=models.UniqueConstraint(fields=('ue', 'inscription_periode'), name='ue-inscription-periode'),
        ),
        migrations.AddConstraint(
            model_name='inscriptionperiode',
            constraint=models.UniqueConstraint(fields=('inscription', 'periode'), name='inscription-periode'),
        ),
    ]
