# Generated by Django 3.0.2 on 2020-04-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0044_inscription_moyenne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='moy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='moy_post_delib',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
