# Generated by Django 3.0.2 on 2020-04-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0045_auto_20200403_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionperiode',
            name='ne',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
