# Generated by Django 3.0.2 on 2020-04-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0046_inscriptionperiode_ne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='archive',
        ),
        migrations.AddField(
            model_name='formation',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
