# Generated by Django 3.0.2 on 2020-04-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0047_auto_20200405_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='scolar.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scolar.Formation'),
        ),
    ]
