# Generated by Django 3.0.2 on 2020-04-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0048_auto_20200406_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='scolar.Etudiant'),
        ),
    ]
