# Generated by Django 3.0.2 on 2020-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0049_auto_20200406_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='statut',
        ),
        migrations.AlterField(
            model_name='inscription',
            name='decision_jury',
            field=models.CharField(blank=True, choices=[('C', 'En cours'), ('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('R', 'Redouble'), ('F', 'Abandon'), ('M', 'Maladie'), ('N', 'Non Admis')], default='F', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='rang',
            field=models.PositiveSmallIntegerField(blank=True, default=1000, null=True),
        ),
    ]
