# Generated by Django 3.0.2 on 2020-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0050_auto_20200407_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
