# Generated by Django 3.0.2 on 2020-04-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0052_auto_20200407_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='type',
            field=models.CharField(choices=[('F', 'UE Fondamentale'), ('M', 'UE Méthodologique'), ('T', 'UE Transversale'), ('D', 'UE Découverte')], max_length=1),
        ),
    ]
