# Generated by Django 3.0.2 on 2020-04-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0054_auto_20200408_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulessuivis',
            name='periode',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='groupe',
        ),
    ]
