# Generated by Django 3.0.2 on 2020-04-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0055_auto_20200408_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='annee_univ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.AnneeUniv'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='periode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Periode'),
        ),
    ]
