# Generated by Django 3.0.2 on 2020-04-10 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0056_auto_20200409_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Enseignant'),
        ),
        migrations.DeleteModel(
            name='PeriodeAnnee',
        ),
    ]
