# Generated by Django 3.0.2 on 2020-04-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0057_auto_20200410_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierecompetenceelement',
            name='competence_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competence_elements', to='scolar.CompetenceElement'),
        ),
    ]
