# Generated by Django 3.0.2 on 2020-04-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0058_auto_20200411_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='titre_a',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
