# Generated by Django 3.0.2 on 2020-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0059_programme_titre_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplome',
            name='intitule_a',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
