# Generated by Django 3.0.2 on 2020-04-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0060_diplome_intitule_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='responsable',
        ),
        migrations.AddField(
            model_name='programme',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Enseignant'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='decision_jury',
            field=models.CharField(blank=True, choices=[('C', 'En cours'), ('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('R', 'Redouble'), ('F', 'Abandon'), ('M', 'Maladie'), ('N', 'Non Admis'), ('X', 'Non Inscrit')], default='F', max_length=2, null=True),
        ),
    ]
