# Generated by Django 3.0.2 on 2020-04-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0061_auto_20200414_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='responsable',
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('intitule_a', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Enseignant')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Departement'),
        ),
    ]
