# Generated by Django 3.0.2 on 2020-04-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0062_auto_20200414_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='intitule_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='intitule',
            field=models.CharField(max_length=100),
        ),
    ]
