# Generated by Django 3.0.2 on 2020-04-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0064_auto_20200415_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='webpage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
