# Generated by Django 3.0.2 on 2020-04-19 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0065_enseignant_webpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='activite_extra',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='activite_extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('eps', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_a', models.CharField(blank=True, max_length=50, null=True)),
                ('eps_a', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom_a', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('bureau', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
