# Generated by Django 3.0.2 on 2020-04-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0067_auto_20200419_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='mention',
            field=models.CharField(blank=True, choices=[('T', 'Très Bien'), ('B', 'Bien'), ('A', 'Assez Bien'), ('P', 'Passable'), ('F', 'Ajournement')], default='N', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('depot_biblio', models.BooleanField(default=False)),
                ('mention', models.CharField(choices=[('T', 'Très Bien'), ('B', 'Bien'), ('A', 'Assez Bien'), ('P', 'Passable'), ('F', 'Ajournement')], max_length=2)),
                ('groupe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Groupe')),
                ('invite1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite1', to='scolar.Enseignant')),
                ('invite2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite2', to='scolar.Enseignant')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president', to='scolar.Enseignant')),
                ('rapporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapporteur', to='scolar.Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='PFE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=100, null=True)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('echeancier', models.TextField(blank=True, null=True)),
                ('bibliographie', models.TextField(blank=True, null=True)),
                ('groupe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Groupe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='soutenance',
            constraint=models.UniqueConstraint(fields=('groupe',), name='groupe-soutenance'),
        ),
        migrations.AddConstraint(
            model_name='pfe',
            constraint=models.UniqueConstraint(fields=('groupe',), name='groupe-pfe'),
        ),
    ]
