# Generated by Django 3.0.2 on 2020-04-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0068_auto_20200423_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='mention',
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='mention',
            field=models.CharField(choices=[('T', 'Très Bien'), ('B', 'Bien'), ('A', 'Assez Bien'), ('P', 'Passable'), ('F', 'Ajournement')], default='F', max_length=2),
        ),
    ]
