# Generated by Django 3.0.2 on 2020-04-24 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0069_auto_20200423_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='mention',
        ),
        migrations.AddField(
            model_name='inscription',
            name='mention',
            field=models.CharField(blank=True, choices=[('T', 'Très Bien'), ('B', 'Bien'), ('A', 'Assez Bien'), ('P', 'Passable'), ('F', 'Ajournement')], default='F', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='encadreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encadreur', to='scolar.Enseignant'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='examinateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinateur', to='scolar.Enseignant'),
        ),
    ]
