# Generated by Django 3.0.2 on 2020-05-08 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0070_auto_20200424_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionperiode',
            name='rang',
            field=models.PositiveSmallIntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='matierecompetenceelement',
            name='competence_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_elements', to='scolar.CompetenceElement'),
        ),
        migrations.AlterField(
            model_name='matierecompetenceelement',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Matiere'),
        ),
    ]
