# Generated by Django 3.0.2 on 2020-06-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0072_auto_20200522_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='vh_cours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='vh_td',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
