# Generated by Django 3.0.2 on 2020-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0073_auto_20200602_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplome',
            name='domaine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diplome',
            name='filiere',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
