# Generated by Django 3.0.2 on 2020-06-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0074_auto_20200603_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodeprogramme',
            name='code',
            field=models.CharField(blank=True, choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='code',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2, null=True),
        ),
    ]
