# Generated by Django 3.0.2 on 2020-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0077_auto_20200609_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
