# Generated by Django 3.0.2 on 2020-06-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0078_specialite_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='moy_post_delib',
        ),
        migrations.RemoveField(
            model_name='inscriptionperiode',
            name='moy_post_delib',
        ),
        migrations.RemoveField(
            model_name='resultatue',
            name='moy_post_delib',
        ),
    ]
