# Generated by Django 3.0.2 on 2020-06-21 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0079_auto_20200615_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscrits', to='scolar.Groupe'),
        ),
    ]
