# Generated by Django 3.0.2 on 2020-06-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0080_auto_20200621_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='encadreur',
        ),
        migrations.AddField(
            model_name='pfe',
            name='encadreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Enseignant'),
        ),
        migrations.AddField(
            model_name='pfe',
            name='promoteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='invite1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='invite2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
