# Generated by Django 3.0.2 on 2020-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0082_auto_20200622_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='cycle_intitule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='cycle_ordre',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activite',
            name='type',
            field=models.CharField(choices=[('C', 'Cours'), ('TD', 'Travail Dirigé'), ('TP', 'Travail Pratique'), ('P', 'Projet'), ('E_CI', 'CI'), ('E_CF', 'CF'), ('E_CR', 'CR'), ('E_In', 'Interrogation'), ('E_TP', 'Test TP'), ('PFE_Enc', 'Encadrement PFE'), ('PFE_Sout', 'Soutenance PFE'), ('Mem_Enc', 'Encadrement Master'), ('Mem_Sout', 'Soutenance Master')], max_length=10),
        ),
        migrations.AlterField(
            model_name='charge',
            name='vh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='charge',
            name='vh_eq_td',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='type',
            field=models.CharField(choices=[('CF', 'Contrôle Final'), ('CI', 'Contrôle Intérmédiaire'), ('INT', 'Interrogation'), ('TP', 'Travail Pratique'), ('PR', 'Projet'), ('CC', 'Contrôle Continu'), ('Rapporteur', 'PFE: Evaluation du rapport'), ('Jury', 'PFE: Evaluation du jury'), ('Encadreur', "PFE: Evaluation de l'encadreur"), ('Rapport', 'Master: Evaluation du rapport'), ('Soutenance', "Master: Evaluation de l'oral"), ('Poster', 'Master: Evaluation du Poster')], max_length=15),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='edt',
            field=models.TextField(blank=True, default='Agenda Empty', null=True),
        ),
    ]
