# Generated by Django 3.0.2 on 2020-06-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0083_auto_20200626_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodeprogramme',
            name='code',
            field=models.CharField(blank=True, choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S5+S6', 'Semestre 6')], max_length=10, null=True),
        ),
    ]
