# Generated by Django 3.0.2 on 2020-06-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0084_auto_20200626_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='mention',
            field=models.CharField(blank=True, choices=[('T', 'Très Bien'), ('B', 'Bien'), ('A', 'Assez Bien'), ('P', 'Passable'), ('F', 'Ajournement'), ('X', 'Non concerné')], default='X', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='periodeprogramme',
            name='code',
            field=models.CharField(blank=True, choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S5+S6', 'Semestre 5+6')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='intitule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
