# Generated by Django 3.0.2 on 2020-07-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0086_auto_20200628_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionperiode',
            name='periodepgm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.PeriodeProgramme'),
        ),
    ]
