# Generated by Django 3.0.2 on 2020-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0088_auto_20200709_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
    ]
