# Generated by Django 3.0.2 on 2020-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0089_auto_20200710_1437'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matierecompetenceelement',
            index=models.Index(fields=['matiere', 'competence_element'], name='scolar_mati_matiere_79e054_idx'),
        ),
    ]
