# Generated by Django 3.0.2 on 2020-07-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0090_auto_20200713_0444'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activite',
            index=models.Index(fields=['module'], name='scolar_acti_module__2fc803_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['realisee_par'], name='scolar_char_realise_7dcfdc_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['formation', 'periode'], name='scolar_modu_formati_af8b17_idx'),
        ),
        migrations.AddIndex(
            model_name='modulessuivis',
            index=models.Index(fields=['module', 'groupe'], name='scolar_modu_module__72778d_idx'),
        ),
    ]
