# Generated by Django 3.0.2 on 2020-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0091_auto_20200713_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cours_na',
            field=models.BooleanField(default=False),
        ),
    ]
