# Generated by Django 3.0.2 on 2020-07-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0092_question_cours_na'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscriptionperiode',
            name='rang',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
