# Generated by Django 3.0.2 on 2020-07-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0093_auto_20200720_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('code_postal', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='addresse_principale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='interne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='residence_univ',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='situation',
            field=models.CharField(blank=True, choices=[('A', 'En activité'), ('D', 'Mise en disponibilité'), ('T', 'Détachement'), ('M', 'Congé de Maladie'), ('I', 'Invalidité'), ('R', 'Retraité'), ('X', 'Départ: Mutation, Démission, ...')], default='A', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='type',
            field=models.CharField(choices=[('CF', 'Contrôle Final'), ('CI', 'Contrôle Intérmédiaire'), ('INT1', 'Interrogation'), ('INT2', 'Interrogation'), ('INT3', 'Interrogation'), ('INT4', 'Interrogation'), ('TP1', 'Travail Pratique'), ('TP2', 'Travail Pratique'), ('TP3', 'Travail Pratique'), ('TP4', 'Travail Pratique'), ('PR1', 'Projet'), ('PR2', 'Projet'), ('PR3', 'Projet'), ('CC', 'Contrôle Continu'), ('Rapporteur', 'PFE: Evaluation du rapport'), ('Jury', 'PFE: Evaluation du jury'), ('Encadreur', "PFE: Evaluation de l'encadreur"), ('Rapport', 'Master: Evaluation du rapport'), ('Soutenance', "Master: Evaluation de l'oral"), ('Poster', 'Master: Evaluation du Poster')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('type', 'module'), name='eval-module'),
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='scolar.Wilaya'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='commune_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Commune'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='wilaya_naissance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Wilaya'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='wilaya_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origines', to='scolar.Wilaya'),
        ),
    ]
