# Generated by Django 3.0.2 on 2020-07-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0094_auto_20200723_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfe',
            name='encadrant',
        ),
        migrations.AddField(
            model_name='activite',
            name='repartir_entre_intervenants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pfe',
            name='coencadrants',
            field=models.ManyToManyField(blank=True, related_name='pfes', to='scolar.Enseignant'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='coencadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coencadrant', to='scolar.Enseignant'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_naissance_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
