# Generated by Django 3.0.2 on 2020-07-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0095_auto_20200724_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteChargeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Cours'), ('TD', 'Travail Dirigé'), ('TP', 'Travail Pratique'), ('P', 'Projet'), ('E_CI', 'CI'), ('E_CF', 'CF'), ('E_CR', 'CR'), ('E_In', 'Interrogation'), ('E_TP', 'Test TP'), ('PFE_Enc', 'Encadrement PFE'), ('PFE_Sout', 'Soutenance PFE'), ('Mem_Enc', 'Encadrement Master'), ('Mem_Sout', 'Soutenance Master')], max_length=10)),
                ('vh', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vh_eq_td', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('repeter_chaque_semaine', models.BooleanField(default=True)),
                ('repartir_entre_intervenants', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='activitechargeconfig',
            constraint=models.UniqueConstraint(fields=('type',), name='activite-charge_config'),
        ),
        migrations.AddField(
            model_name='charge',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.ActiviteChargeConfig'),
        ),
    ]
