# Generated by Django 3.0.2 on 2020-07-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0096_auto_20200724_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitechargeconfig',
            name='titre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activitechargeconfig',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
