# Generated by Django 3.0.2 on 2020-07-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0097_auto_20200724_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='config',
        ),
    ]
