# Generated by Django 3.0.2 on 2020-07-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0098_remove_charge_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='assesseur1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assesseur1', to='scolar.Enseignant'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='assesseur2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assesseur2', to='scolar.Enseignant'),
        ),
    ]
