# Generated by Django 3.0.2 on 2020-07-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0099_auto_20200725_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitechargeconfig',
            name='categorie',
            field=models.CharField(choices=[('E', 'Enseignement'), ('C', 'Encadrement'), ('S', 'Surveillance'), ('A', 'Responsabilite Administrative'), ('M', 'Mission'), ('R', 'Réunion')], max_length=5, null=True),
        ),
    ]
