# Generated by Django 3.0.2 on 2020-07-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0100_activitechargeconfig_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitechargeconfig',
            name='categorie',
            field=models.CharField(choices=[('E', 'Enseignement'), ('C', 'Encadrement'), ('J', 'Jury'), ('S', 'Surveillance'), ('A', 'Responsabilite Administrative'), ('M', 'Mission'), ('R', 'Réunion')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='type',
            field=models.CharField(choices=[('E', 'Enseignement'), ('C', 'Encadrement'), ('J', 'Jury'), ('S', 'Surveillance'), ('A', 'Responsabilite Administrative'), ('M', 'Mission'), ('R', 'Réunion')], max_length=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='scolar.Formation'),
        ),
    ]
