# Generated by Django 3.0.2 on 2020-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0101_auto_20200725_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='ects_post_delib',
        ),
        migrations.AlterField(
            model_name='inscription',
            name='decision_jury',
            field=models.CharField(blank=True, choices=[('C', 'En cours'), ('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('R', 'Redouble'), ('F', 'Abandon'), ('M', 'Maladie'), ('N', 'Non Admis'), ('X', 'Non Inscrit')], default='X', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='rang',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
