# Generated by Django 3.0.2 on 2020-08-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0102_auto_20200728_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
