# Generated by Django 3.0.2 on 2020-08-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0103_auto_20200807_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soutenance',
            old_name='depot_biblio',
            new_name='depotbiblio',
        ),
    ]
