# Generated by Django 3.0.2 on 2020-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0104_auto_20200815_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='depot_biblio',
            field=models.SmallIntegerField(choices=[(0, 'Non'), (1, 'Oui'), (2, 'Oui avec des corrections à faire')], default=0),
        ),
    ]
