# Generated by Django 3.0.2 on 2020-08-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0105_soutenance_depot_biblio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='depotbiblio',
        ),
    ]
