# Generated by Django 3.0.2 on 2020-08-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0106_remove_soutenance_depotbiblio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='competence_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='scolar.CompetenceFamily'),
        ),
        migrations.AlterField(
            model_name='competenceelement',
            name='competence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_elements', to='scolar.Competence'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='depot_biblio',
            field=models.SmallIntegerField(choices=[(1, 'Oui'), (2, 'Oui avec des corrections à faire'), (3, 'Non')], default=3),
        ),
        migrations.CreateModel(
            name='NoteCompetenceElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('evaluation_competence_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.EvaluationCompetenceElement')),
                ('note_globale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Note')),
            ],
        ),
        migrations.AddConstraint(
            model_name='notecompetenceelement',
            constraint=models.UniqueConstraint(fields=('evaluation_competence_element', 'note_globale'), name='evaluation_competence_element_note_globale'),
        ),
    ]
