# Generated by Django 3.0.2 on 2020-08-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0107_auto_20200824_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfe',
            name='statut_validation',
            field=models.CharField(choices=[('S', 'Soumis'), ('W', 'Attente Validation'), ('RR', 'Révision Requise'), ('RT', 'Révision Terminée'), ('V', 'Validé'), ('N', 'Non Valide')], default='S', max_length=2),
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.CharField(choices=[('V', 'Valide'), ('R', 'Réserve'), ('N', 'Non Valide'), ('X', 'Non Renseigné')], default='X', max_length=1)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('debut', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Enseignant')),
                ('pfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='scolar.PFE')),
            ],
        ),
        migrations.AddConstraint(
            model_name='validation',
            constraint=models.UniqueConstraint(fields=('pfe', 'expert'), name='pfe-expert'),
        ),
    ]
