# Generated by Django 3.0.2 on 2020-09-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0108_auto_20200830_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pfe',
            name='diplome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Diplome'),
        ),
        migrations.AddField(
            model_name='pfe',
            name='reserve_pour',
            field=models.ManyToManyField(to='scolar.Inscription'),
        ),
        migrations.AddField(
            model_name='pfe',
            name='specialites',
            field=models.ManyToManyField(to='scolar.Specialite'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='scolar.Feedback'),
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('sigle', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('R', 'Laboratoire/Centre de Recherche'), ('E', 'Entreprise'), ('A', 'Administration')], max_length=2)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Pays')),
            ],
        ),
        migrations.AddField(
            model_name='pfe',
            name='organisme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Organisme'),
        ),
    ]
