# Generated by Django 3.0.2 on 2020-09-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0109_auto_20200902_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfe',
            name='bibliographie',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='echeancier',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='intitule',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='objectifs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='promoteur',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='resume',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='statut_validation',
            field=models.CharField(choices=[('S', 'Soumis'), ('W', 'Validation en cours'), ('RR', 'Révision Requise'), ('RT', 'Révision Terminée'), ('V', 'Validé'), ('N', 'Non Valide')], default='S', max_length=2),
        ),
    ]
