# Generated by Django 3.0.2 on 2020-09-04 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0110_auto_20200904_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='sigle',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Saisir en majuscule')]),
        ),
    ]
