# Generated by Django 3.0.2 on 2020-09-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0111_auto_20200904_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='pays',
            field=models.ForeignKey(default='DZ', on_delete=django.db.models.deletion.CASCADE, to='scolar.Pays'),
        ),
    ]
