# Generated by Django 3.0.2 on 2020-09-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0112_auto_20200904_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfe',
            name='diplome',
        ),
        migrations.AddField(
            model_name='pfe',
            name='type',
            field=models.CharField(choices=[('P', 'PFE'), ('M', 'Master')], default='P', max_length=2),
        ),
    ]
