# Generated by Django 3.0.2 on 2020-09-05 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0114_auto_20200904_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisme',
            name='nature',
            field=models.CharField(blank=True, choices=[('P', 'Publique'), ('PR', 'Privée'), ('M', 'Mixte')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='organisme',
            name='secteur',
            field=models.CharField(blank=True, choices=[('S', 'Services'), ('C', 'Commercial'), ('I', 'Industriel')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='organisme',
            name='statut',
            field=models.CharField(blank=True, choices=[('SPA', 'Société Par Actions'), ('SARL', 'Société Anonyme à Résponsabilité Limitée'), ('EURL', 'Entreprise Unanime à Résponsabilité Limitée')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='organisme',
            name='taille',
            field=models.CharField(blank=True, choices=[('10', 'Moins de 10 salariés'), ('100', 'Entre 10 et 100 salariés'), ('500', 'Entre 100 et 500 salariés'), ('1000', 'Plus de 500 salariés')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='sigle',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Saisir en majuscule')]),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='type',
            field=models.CharField(choices=[('R', 'Laboratoire / Centre de Recherche'), ('E', 'Entreprise'), ('A', 'Administration')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='moyens_informatiques',
            field=models.CharField(blank=True, choices=[('ESI', "A la charge de l'école"), ('ORG', "A la charge de l'organisme d'accueil")], max_length=3, null=True),
        ),
    ]
