# Generated by Django 3.0.2 on 2020-09-05 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0115_auto_20200905_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='sigle',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z_\\-\\&\\@]*$', 'Saisir en majuscule')]),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='organisme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Organisme'),
        ),
    ]
