# Generated by Django 3.0.2 on 2020-09-06 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0116_auto_20200905_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfe',
            name='projet_recherche',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='sigle',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z_\\-\\&\\@\\ ]*$', 'Saisir en majuscule')]),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='antecedents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='bibliographie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
