# Generated by Django 3.0.2 on 2020-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0117_auto_20200906_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='fin',
            field=models.DateField(null=True),
        ),
    ]
