# Generated by Django 3.0.2 on 2020-09-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0118_auto_20200906_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfe',
            name='email_promoteur',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='statut_validation',
            field=models.CharField(choices=[('S', 'Soumis'), ('W', 'Validation en cours'), ('RR', 'Révision Requise'), ('RT', 'Révision Terminée'), ('LR', 'Levée de Réserve'), ('V', 'Validé'), ('N', 'Rejeté')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='validation',
            name='avis',
            field=models.CharField(choices=[('V', 'Avis favorable'), ('SR', 'Avis favorable avec réserves mineures'), ('MR', 'Avis favorable avec réserves majeures'), ('N', 'Avis défavorable'), ('X', 'Non Renseigné')], default='X', max_length=2),
        ),
    ]
