# Generated by Django 3.0.2 on 2020-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0125_auto_20200923_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfe',
            name='reponse_aux_experts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
