# Generated by Django 3.0.2 on 2020-09-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0126_pfe_reponse_aux_experts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('capacite', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('activite', 'date', 'heure_debut', 'heure_fin'), name='seance'),
        ),
        migrations.AddConstraint(
            model_name='salle',
            constraint=models.UniqueConstraint(fields=('code',), name='salle-code'),
        ),
        migrations.AddField(
            model_name='seance',
            name='salles',
            field=models.ManyToManyField(blank=True, null=True, to='scolar.Salle'),
        ),
    ]
