# Generated by Django 3.0.2 on 2020-09-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0127_auto_20200928_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='salles',
            field=models.ManyToManyField(blank=True, to='scolar.Salle'),
        ),
        migrations.CreateModel(
            name='SurveillanceEnseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Enseignant')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Salle')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Seance')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationPlaceEtudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(default=0)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Inscription')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Salle')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Seance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='surveillanceenseignant',
            constraint=models.UniqueConstraint(fields=('enseignant', 'seance'), name='surveillance_enseignant'),
        ),
        migrations.AddConstraint(
            model_name='reservationplaceetudiant',
            constraint=models.UniqueConstraint(fields=('inscription', 'seance'), name='reservation_place_etudiant'),
        ),
    ]
