# Generated by Django 3.0.2 on 2020-09-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0128_auto_20200928_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='cible',
            field=models.ManyToManyField(blank=True, related_name='activites', to='scolar.Groupe'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
