# Generated by Django 3.0.2 on 2020-09-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0129_auto_20200930_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='type',
            field=models.CharField(choices=[('C', 'Cours'), ('TD', 'Travail Dirigé'), ('TP', 'Travail Pratique'), ('P', 'Projet'), ('E_CI', 'Contrôle Intermédiaire'), ('E_CF', 'Contrôle Final'), ('E_CR', 'Contrôle de Remplacement'), ('E_In', 'Interrogation'), ('E_TP', 'Test TP'), ('PFE_Enc', 'Encadrement PFE'), ('PFE_Sout', 'Soutenance PFE'), ('Mem_Enc', 'Encadrement Master'), ('Mem_Sout', 'Soutenance Master')], max_length=10),
        ),
    ]
