# Generated by Django 3.0.2 on 2020-10-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0130_auto_20200930_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='decision_jury',
            field=models.CharField(blank=True, choices=[('C', 'En cours'), ('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('R', 'Redouble'), ('F', 'Abandon'), ('M', 'Maladie'), ('M1', 'Raisons médicales'), ('M2', 'Raisons personnelles'), ('M3', 'Raisons personnelles (Covid 19)'), ('M4', 'Raisons familiales'), ('N', 'Non Admis'), ('X', 'Non Inscrit')], default='X', max_length=2, null=True),
        ),
    ]
