# Generated by Django 3.0.2 on 2020-10-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0132_auto_20201017_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='capacite',
        ),
        migrations.AddField(
            model_name='departement',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='admin'),
        ),
    ]
