# Generated by Django 3.0.2 on 2020-10-21 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0133_auto_20201021_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sigle', models.CharField(max_length=10)),
                ('adresse', models.TextField()),
                ('tel', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\+]*$', "Que des chiffres sans espaces et le + pour l'international")])),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='admin')),
                ('header', models.ImageField(blank=True, null=True, upload_to='admin')),
                ('footer', models.ImageField(blank=True, null=True, upload_to='admin')),
            ],
        ),
        migrations.AlterField(
            model_name='pfe',
            name='tel_promoteur',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\+]*$', "Que des chiffres sans espaces et le + pour l'international")]),
        ),
    ]
