# Generated by Django 3.0.2 on 2020-10-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0134_auto_20201021_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='admin'),
        ),
    ]
