# Generated by Django 3.0.2 on 2020-10-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0136_institution_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo_bis',
            field=models.ImageField(blank=True, null=True, upload_to='admin'),
        ),
    ]
