# Generated by Django 3.0.2 on 2020-10-22 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0137_institution_logo_bis'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\+]*$', "Que des chiffres sans espaces et le + pour l'international")]),
        ),
        migrations.AddField(
            model_name='institution',
            name='nom_a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
