# Generated by Django 3.0.2 on 2020-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0138_auto_20201022_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='illustration_cursus',
            field=models.ImageField(blank=True, null=True, upload_to='admin'),
        ),
    ]
