# Generated by Django 3.0.2 on 2020-10-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0139_institution_illustration_cursus'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='ville_a',
            field=models.CharField(default='', max_length=50),
        ),
    ]
