# Generated by Django 3.0.2 on 2020-10-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0141_auto_20201025_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='moy_ue',
            field=models.BooleanField(default=False),
        ),
    ]
