# Generated by Django 3.0.2 on 2020-11-05 10:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import scolar.models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0147_auto_20201104_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='numero_securite_sociale',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\+]*$', 'Que des chiffres sans espaces')]),
        ),
        migrations.AddField(
            model_name='inscription',
            name='quittance',
            field=models.ImageField(blank=True, null=True, upload_to='quittances'),
        ),
        migrations.AddField(
            model_name='programme',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.Personnel'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='decision_jury',
            field=models.CharField(blank=True, choices=[('C', 'Inscrit'), ('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('AC', 'Admis au Concours'), ('CR', 'Admis au Concours avec Rachat'), ('R', 'Redouble'), ('AJ', 'Ajournement'), ('F', 'Abandon'), ('M', 'Maladie'), ('M1', 'Congé académique (année blanche) pour raisons médicales'), ('M2', 'Congé académique (année blanche) pour raisons personnelles'), ('M3', 'Congé académique (année blanche) pour raisons personnelles (Covid 19)'), ('M4', 'Congé académique (année blanche) pour raisons familiales'), ('N', 'Non Admis'), ('X', 'Non Inscrit')], default='X', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='proposition_decision_jury',
            field=models.CharField(blank=True, choices=[('C', 'Inscrit'), ('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('AC', 'Admis au Concours'), ('CR', 'Admis au Concours avec Rachat'), ('R', 'Redouble'), ('AJ', 'Ajournement'), ('F', 'Abandon'), ('M', 'Maladie'), ('M1', 'Congé académique (année blanche) pour raisons médicales'), ('M2', 'Congé académique (année blanche) pour raisons personnelles'), ('M3', 'Congé académique (année blanche) pour raisons personnelles (Covid 19)'), ('M4', 'Congé académique (année blanche) pour raisons familiales'), ('N', 'Non Admis'), ('X', 'Non Inscrit')], default='X', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='ResidenceUniv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.TextField()),
                ('tel', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9\\+]*$', "Que des chiffres sans espaces et le + pour l'international")])),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Commune')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolar.Wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='Preinscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interne', models.BooleanField(blank=True, default=False, null=True)),
                ('addresse_principale', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tmp', validators=[scolar.models.validate_image])),
                ('quittance', models.ImageField(blank=True, null=True, upload_to='tmp', validators=[scolar.models.validate_image])),
                ('tel', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\+]*$', "Que des chiffres sans espaces et le + pour l'international")])),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\+]*$', 'Que des chiffres sans espaces')])),
                ('commune_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Commune')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scolar.Inscription')),
                ('residence_univ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolar.ResidenceUniv')),
                ('wilaya_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolar.Wilaya')),
            ],
        ),
    ]
