# Generated by Django 3.0.2 on 2020-11-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0148_auto_20201105_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preinscription',
            old_name='addresse_principale',
            new_name='adresse_principale',
        ),
    ]
