# Generated by Django 3.0.2 on 2020-11-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0149_auto_20201105_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='reglement',
            field=models.FileField(blank=True, null=True, upload_to='admin'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='interne',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
