# Generated by Django 3.0.2 on 2020-11-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0150_auto_20201106_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfe',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
