# Generated by Django 3.0.2 on 2020-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0151_pfe_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('calendarId', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='salle',
            name='gcal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='googlecalendar',
            constraint=models.UniqueConstraint(fields=('code',), name='gcal-code'),
        ),
    ]
