# Generated by Django 3.0.2 on 2020-11-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0152_auto_20201112_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='gcal_email',
        ),
        migrations.AddField(
            model_name='salle',
            name='calendarId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
