# Generated by Django 3.0.2 on 2020-11-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0153_auto_20201112_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
