# Generated by Django 3.0.2 on 2020-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0154_auto_20201119_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
