# Generated by Django 3.0.2 on 2020-12-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0156_pv_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='decision_jury',
            field=models.CharField(blank=True, choices=[('C', 'Inscrit'), ('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('AC', 'Admis au Concours'), ('CR', 'Admis au Concours avec Rachat'), ('R', 'Redouble'), ('AJ', 'Ajournement'), ('P', 'Prolongation'), ('F', 'Abandon'), ('M', 'Maladie'), ('M1', 'Congé académique (année blanche) pour raisons médicales'), ('M2', 'Congé académique (année blanche) pour raisons personnelles'), ('M3', 'Congé académique (année blanche) pour raisons personnelles (Covid 19)'), ('M4', 'Congé académique (année blanche) pour raisons familiales'), ('N', 'Non Admis'), ('X', 'Non Inscrit')], default='X', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='proposition_decision_jury',
            field=models.CharField(blank=True, choices=[('C', 'Inscrit'), ('A', 'Admis'), ('AR', 'Admis avec Rachat'), ('AC', 'Admis au Concours'), ('CR', 'Admis au Concours avec Rachat'), ('R', 'Redouble'), ('AJ', 'Ajournement'), ('P', 'Prolongation'), ('F', 'Abandon'), ('M', 'Maladie'), ('M1', 'Congé académique (année blanche) pour raisons médicales'), ('M2', 'Congé académique (année blanche) pour raisons personnelles'), ('M3', 'Congé académique (année blanche) pour raisons personnelles (Covid 19)'), ('M4', 'Congé académique (année blanche) pour raisons familiales'), ('N', 'Non Admis'), ('X', 'Non Inscrit')], default='X', max_length=2, null=True),
        ),
    ]
