# Generated by Django 3.0.2 on 2020-12-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0157_auto_20201208_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='interne',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='interne',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
