# Generated by Django 3.1.7 on 2021-04-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0160_auto_20210415_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chapitre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scolar.chapitre'),
        ),
    ]
