# Generated by Django 3.1.7 on 2021-04-29 12:56

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0163_auto_20210425_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bordereau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_allouee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='DA', max_digits=9),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_allouee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('DA', 'DA')], default='DA', editable=False, max_length=3),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deseingnation', models.CharField(blank=True, max_length=200, null=True)),
                ('montant_currency', djmoney.models.fields.CurrencyField(choices=[('DA', 'DA')], default='DA', editable=False, max_length=3)),
                ('montant', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='DA', max_digits=9)),
                ('bordreau', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scolar.bordereau')),
                ('credit', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scolar.credit')),
            ],
        ),
        migrations.AddField(
            model_name='bordereau',
            name='credit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scolar.credit'),
        ),
    ]
