# Generated by Django 3.1.7 on 2021-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0164_auto_20210429_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereau',
            name='deseingnation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bordereau',
            name='regisseur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
