# Generated by Django 3.1.7 on 2021-05-25 15:38

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0167_auto_20210525_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='montant',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='DZD', max_digits=9),
        ),
        migrations.AlterField(
            model_name='piece',
            name='montant_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('DZD', 'DZD')], default='DZD', editable=False, max_length=3),
        ),
    ]
