# Generated by Django 3.1.7 on 2021-05-26 10:14

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0169_auto_20210525_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit_reste',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='DZD', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_reste_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('DZD', 'DZD')], default='DZD', editable=False, max_length=3),
        ),
    ]
