# Generated by Django 2.2.10 on 2021-10-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0171_auto_20210526_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
