# Generated by Django 2.2.10 on 2021-10-18 13:46

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scolar', '0173_auto_20211018_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit_allouee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='DA', max_digits=9),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_allouee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('DZD', 'DZD')], default='DA', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_reste',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='DA', max_digits=9),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_reste_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('DZD', 'DZD')], default='DA', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='piece',
            name='montant',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='DA', max_digits=9),
        ),
        migrations.AlterField(
            model_name='piece',
            name='montant_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('DZD', 'DZD')], default='DA', editable=False, max_length=3),
        ),
    ]
